version: '3.4'

services:
  netschool_postgresql:
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
    ports:
      - "45432:5432"
    networks:
      - shared_netschool_net
    volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  netschool_rabbitmq:
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672" 
    networks:
      - shared_netschool_net
    volumes:      
      - ./rabbitmq:/var/lib/rabbitmq
    

  netschool_api:
    ports:
      - "10000:8080"
    networks:
      - shared_netschool_net
    env_file:
      - env.api

  dsrnetschool_worker_1:
    networks:
      - shared_netschool_net
    ports:
      - "10001:8080"
    env_file:
      - env.worker

  dsrnetschool_worker_2:
    networks:
      - shared_netschool_net
    ports:
      - "10002:8080"
    env_file:
      - env.worker


networks:
  shared_netschool_net:
    name: net_school
    driver: bridge